### ISSUE TITLE
Cannot read property 'getSteamID64' of null

### ISSUE THREAD

**Issue by Foltos2016** [DoctorMcKay/node-steamcommunity#102]
TypeError: Cannot read property 'getSteamID64' of null
    at SteamCommunity.getUserInventory (/home/csgo2/node_modules/steamcommunity/components/users.js:240:38)
    at TradeOfferManager.loadUserInventory (/home/csgo2/node_modules/steam-tradeoffer-manager/lib/index.js:135:18)
    at TradeOfferManager.loadInventory (/home/csgo2/node_modules/steam-tradeoffer-manager/lib/index.js:131:7)

If not logined the bot.

You can fix?

**Comment by DoctorMcKay** [comment]
If you aren't logged into the bot, you can't get the bot's inventory. Login first.
