### ISSUE TITLE
Error - SSL3_GET_RECORD

### ISSUE THREAD

**Issue by pwservice** [DoctorMcKay/node-steamcommunity#116]
How do I fix this error ?

`[Error: 140073901754144:error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed
or bad record mac:../deps/openssl/openssl/ssl/s3_pkt.c:518:

undefined:0

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Request._callback (/root/bot/steambottest2.js:61:20)
    at Request.self.callback (/root/bot/node_modules/request/request.js:354:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/root/bot/node_modules/request/request.js:1207:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/root/bot/node_modules/request/request.js:1153:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

loading inventory: Error: 140096469796640:error:1408F119:SSL routines:SSL3_GET_RECORD:
decryption failed or bad record mac:../deps/openssl/openssl/ssl/s3_pkt.c:518:

[14:13:11:154] Message: "Error loading my inventory" at row:1269, Content:
[Error: 140096469796640:error:1408F119:SSL routines:SSL3_GET_RECORD:
decryption failed or bad record mac:../deps/openssl/openssl/ssl/s3_pkt.c:518: ]

/root/bot/steambottest2.js:1009
                                    loadMyInventory();
                                    ^
ReferenceError: loadMyInventory is not defined
    at null._onTimeout

loading inventory: Error: write EPROTO 139841482303264:error:0407006A:
rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01:
../deps/openssl/openssl/crypto/rsa/rsa_pk1.c:103:`

**Comment by DoctorMcKay** [comment]
This doesn't seem to be a problem in node-steamcommunity.
