### ISSUE TITLE
Error: Callback was already called.

### ISSUE THREAD

**Issue by Tutyko2016** [DoctorMcKay/node-steamcommunity#123]
New bugg:

Error: Callback was already called.
    at null._onTimeout (/home/csgobot/node_modules/steamcommunity/node_modules/async/lib/async.js:43:36)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by DoctorMcKay** [comment]
When does this happen? Is that the full stack trace?

**Comment by Tutyko2016** [comment]
Now happen.

(steamcommunity offline)

**Comment by Tutyko2016** [comment]
I get error this:

[31merror[39m: uncaughtException: Error: Callback was already called.
    at null._onTimeout (/home/csgobot/node_modules/steamcommunity/node_modules/async/lib/async.js:43:36)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by Tutyko2016** [comment]
Error polling for trade offers: Error: HTTP error 504

Error: Callback was already called.
    at null._onTimeout (/home/csgo5/node_modules/steamcommunity/node_modules/async/lib/async.js:43:36)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by DoctorMcKay** [comment]
Should be fixed in 3.23.3.

**Comment by Tutyko2016** [comment]
nice work :+1:
