### ISSUE TITLE
TypeError: Cannot read property publickey_mod of undefined

### ISSUE THREAD

**Issue by TheRealGuru** [DoctorMcKay/node-steamcommunity#125]
Not sure the events leading up to this, but a stack trace I recently got. Any idea what the problem might be? There is no trace of me calling something to cause this below so it leads me to believe this is a stack trace for you.

Replaced the full path to xxxpath for security purposes.

```
  [ 'TypeError: Cannot read property \'publickey_mod\' of undefined',
    '    at SteamCommunity.<anonymous> (/xxxpath/node_modules/steamcommunity/index.js:83:11)',
    '    at Request._callback (/xxxpath/node_modules/steamcommunity/components/http.js:62:14)',
    '    at Request.self.callback (/xxxpath/node_modules/steamcommunity/node_modules/request/request.js:187:22)',
    '    at emitTwo (events.js:106:13)',
    '    at Request.emit (events.js:191:7)',
    '    at Request.<anonymous> (/xxxpath/node_modules/steamcommunity/node_modules/request/request.js:1044:10)',
    '    at emitOne (events.js:96:13)',
    '    at Request.emit (events.js:188:7)',
    '    at Gunzip.<anonymous> (/xxxpath/node_modules/steamcommunity/node_modules/request/request.js:965:12)',
    '    at emitNone (events.js:91:20)',
    '    at Gunzip.emit (events.js:185:7)' ] }
```

**Comment by scholtzm** [comment]
https://github.com/DoctorMcKay/node-steamcommunity/issues/124

Make sure you are running latest version.
