### ISSUE TITLE
twofactor.js error when calling finalizeTwoFactor?

### ISSUE THREAD

**Issue by ipaspeak** [DoctorMcKay/node-steamcommunity#13]
So I've started using node steamcommunity for mobile 2FA and I've successfully logged in as well as made an enableTwoFactor() request (i.e. I'm receiving all relevant data from steam like shared_secret, revocation code etc.). But when I call finalizeTwoFactor with the code that was sent to my mobile I'm hit the response body is as follows:

{ success: false, server_time: '1448691372', status: 88 }

and node gives me the error:

/usr/lib/node_modules/steamcommunity/components/twofactor.js:104
				callback(new Error("Error " + body.status));
				^

TypeError: callback is not a function
    at Request._callback (/usr/lib/node_modules/steamcommunity/components/twofactor.js:104:5)
    at Request.self.callback (/usr/lib/node_modules/steamcommunity/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/lib/node_modules/steamcommunity/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/steamcommunity/node_modules/request/request.js:962:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)

I'm aware that these changes are fresh and am wondering if it is something I'm doing wrong or if it is just because the 2FA changes are still incomplete. BTW I'm using v3.11. Thanks.

**Comment by ipaspeak** [comment]
Oh woop s you need to supply shared secret
