### ISSUE TITLE
Unhandled module error

### ISSUE THREAD

**Issue by Freaders** [DoctorMcKay/node-steamcommunity#151]
```
/bot/node_modules/steamcommunity/classes/CSteamUser.js:112
        var url = protocol + "steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/" + hash.substring(0, 2) + "/" + hash;
                                                                                                   ^

TypeError: Cannot read property 'substring' of null
    at Function.CSteamUser.getAvatarURL (/bot/node_modules/steamcommunity/classes/CSteamUser.js:112:93)
    at CSteamUser.getAvatarURL (/bot/node_modules/steamcommunity/classes/CSteamUser.js:121:20)
    at /bot/a.js:1379:23
    at Array.forEach (native)
    at Jackpot.deposit (/bot/a.js:1376:11)
    at /bot/a.js:945:43
    at SteamCommunity.manager._community.httpRequestGet (/bot/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:782:4)
    at Request._callback (/bot/node_modules/steamcommunity/components/http.js:67:15)
    at Request.self.callback (/bot/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
error: Forever detected script exited with code: 1
```

**Comment by scholtzm** [comment]
Seems like this [`RegExp`](https://github.com/DoctorMcKay/node-steamcommunity/blob/master/classes/CSteamUser.js#L61) returned `null`.

Knowing what was inside [`userData`](https://github.com/DoctorMcKay/node-steamcommunity/blob/master/classes/CSteamUser.js#L52) would be useful in this case.
