### ISSUE TITLE
Empty inventory results in "Malformed response" getUserInventoryContents 

### ISSUE THREAD

**Issue by notJackson** [DoctorMcKay/node-steamcommunity#156]
```js
Body: { total_inventory_count: 0, success: 1, rwgrsn: -2 }
```
```js
Error: Malformed response
    at SteamCommunity.<anonymous> (C:\Users\Michael\Documents\GitHub\project\node_modules\steamcommunity\components\users.js:388:15)
    at Request._callback (C:\Users\Michael\Documents\GitHub\project\node_modules\steamcommunity\components\http.js:67:15)
    at Request.self.callback (C:\Users\Michael\Documents\GitHub\project\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\Michael\Documents\GitHub\project\node_modules\request\request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\Michael\Documents\GitHub\project\node_modules\request\request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 ```

https://github.com/DoctorMcKay/node-steamcommunity/blob/master/components/users.js#L388

**Comment by Vankxr** [comment]
https://github.com/DoctorMcKay/node-steamcommunity/pull/155
