### ISSUE TITLE
.toString error

### ISSUE THREAD

**Issue by xLeeJYx** [DoctorMcKay/node-steamcommunity#172]
C:\Users\JingYong-PC\Desktop\BptfAutomaticPro\node_modules\steamcommunity\components\users.js:167
                        "group": groupID.toString(),
                                        ^

TypeError: Cannot read property 'toString' of undefined
    at SteamCommunity.inviteUserToGroup (C:\Users\JingYong-PC\Desktop\BptfAutomaticPro\node_modules\steamcommunity\components\users.js:167:20)
    at TradeOfferManager.manager.on (C:\Users\JingYong-PC\Desktop\BptfAutomaticPro\steambot.js:604:13)
    at emitTwo (events.js:106:13)
    at TradeOfferManager.emit (events.js:191:7)
    at received.forEach (C:\Users\JingYong-PC\Desktop\BptfAutomaticPro\node_modules\steam-tradeoffer-manager\lib\polling.js:237:10)
    at Array.forEach (native)
    at getOffers (C:\Users\JingYong-PC\Desktop\BptfAutomaticPro\node_modules\steam-tradeoffer-manager\lib\polling.js:219:12)
    at Helpers.checkNeededDescriptions (C:\Users\JingYong-PC\Desktop\BptfAutomaticPro\node_modules\steam-tradeoffer-manager\lib\index.js:369:4)
    at Object.exports.checkNeededDescriptions (C:\Users\JingYong-PC\Desktop\BptfAutomaticPro\node_modules\steam-tradeoffer-manager\lib\helpers.js:90:3)
    at _apiCall (C:\Users\JingYong-PC\Desktop\BptfAutomaticPro\node_modules\steam-tradeoffer-manager\lib\index.js:360:11)

**Comment by xLeeJYx** [comment]
not sure what happened, tried reinstalling it and still didnt work

**Comment by Aareksio** [comment]
It's an error with your code.

> **Have a question about the module or coding in general? _Do not create a GitHub issue._ GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/8-node-steamcommunity/). Such issues may be ignored!**

You're using `SteamCommunity.inviteUserToGroup` with 2nd parameter empty (or passing `undefined` there). Check L604 of `steambot.js`.
Don't expect further assistance in this issue.

**Comment by xLeeJYx** [comment]
@Aareksio  ok, ive found out the mistake, i put
`"group64id": "1234567789"` in the json file and i wrote `config.groupid` in the js -_-
