### ISSUE TITLE
Bug with events at getAllGroupAnnouncements (groups.js)

### ISSUE THREAD

**Issue by borianm** [DoctorMcKay/node-steamcommunity#182]
Hello,
I have been looking around the code and what happens when I want to delete a specific event, so I looked at the code and RSS group feed and found out that the function getAllGroupAnnouncements is actually loading both events and announcements. Now this is alright, but there is a problem where the getAllGroupAnnouncements is not checking whether the property author exists (it doesn't exist for events). It would also be useful that the author property returns null, so I could handle events from this function.
```js
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property '0' of undefined
    at /home/node_modules/steamcommunity/components/groups.js:146:35
    at Array.map (native)
    at /home/node_modules/steamcommunity/components/groups.js:140:52
    at Parser.<anonymous> (/home/node_modules/xml2js/lib/parser.js:303:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Object.onclosetag (/home/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/home/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/node_modules/sax/lib/sax.js:889:7)
```

Thank you!

**Comment by DoctorMcKay** [comment]
Fixed in #183.
