### ISSUE TITLE
[Bug] this.httpRequestGet is not a function

### ISSUE THREAD

**Issue by Revadike** [DoctorMcKay/node-steamcommunity#216]
My bot often crashes with the error: `this.httpRequestGet is not a function` referring to [here](https://github.com/DoctorMcKay/node-steamcommunity/blob/master/index.js#L370).
Not sure why it happens, but maybe it has something to do with the `self` variable not being used (dead code)?

**Comment by DoctorMcKay** [comment]
Please show the full stack trace and the code that's calling `resetItemNotifications`.

**Comment by Revadike** [comment]
It doesn't seem to only happen with that function. Perhaps it has something to do with having the instance loaded into an object (instead just 1 variable).

Stack traces:
```
 2019-01-11 | 05:17:53.946 | ERROR | crashBot                       | TypeError: this.getSessionID is not a function
    at Timeout.SteamCommunity.postProfileStatus [as _onTimeout] (C:\Users\Administrator\OneDrive\Projects\NodeJS\node_modules\steamcommunity\components\profile.js:411:27)
    at ontimeout (timers.js:479:15)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)

```

```
 2019-01-10 | 02:09:22.977 | ERROR | crashBot                       | TypeError: this.httpRequestGet is not a function
    at Timeout.SteamCommunity.resetItemNotifications [as _onTimeout] (C:\Users\Administrator\OneDrive\Projects\NodeJS\node_modules\steamcommunity\index.js:370:7)
    at ontimeout (timers.js:473:15)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)

```

Related code snippets:

```
function gotNewSteamInventoryItems(count) {
    if (count === 0) {
        return;
    }

    Logger.info(`Steam inventory gained ${count} new item${numToPlural(count)}`);
    const clearedNotifications = error => {
        if (error) {
            Logger.error(`Failed to clear steam inventory notifications: ${error.message || error}`);
            retryOnError(steam.community.resetItemNotifications, clearedNotifications);
            return;
        }

        Logger.info(`Cleared notifications about new items in steam inventory`);
    };
    refreshSteamWebSession(() => steam.community.resetItemNotifications(clearedNotifications));

    if (config.servermode && steam.idler.apps.length > 0) {
        checkCardApps();
    }
}
```

```
            const newmsg = createSteamUserStatusMsg(appids, appnames);
            const options = {
                appID: appids[0]
            };

            const postedSteamUserStatus = (error, postid) => {
                if (error) {
                    Logger.error(`Failed to post user status: ${error.message || error}`);
                    retryOnError(steam.community.postProfileStatus, newmsg, options, postedSteamUserStatus);
                    return;
                }

                Logger.info(`Successfully posted user status (${postid}) to friends activity`);
            };

            refreshSteamWebSession(() => steam.community.postProfileStatus(newmsg, options, postedSteamUserStatus));

```

**Comment by DoctorMcKay** [comment]
`retryOnError(steam.community.resetItemNotifications, clearedNotifications);`

This is your problem. You need to use `retryOnError(() => steam.community.resetItemNotifications(), clearedNotifications)`. Passing the method like that loses context and `this` no longer refers to the SteamCommunity instance.

**Comment by Revadike** [comment]
Ah, yes, makes sense. I changed it to `retryOnError(() => steam.community.resetItemNotifications(clearedNotifications)).`, will let you know if it happens again.
