### ISSUE TITLE
Crash on http error

### ISSUE THREAD

**Issue by srabouin** [DoctorMcKay/node-steamcommunity#23]
using 3.12.2

```javascript

node_modules/steamcommunity/node_modules/cheerio/lib/parse.js:55
    var oldParent = node.parent || node.root,
                        ^
TypeError: Cannot read property 'parent' of undefined
    at Function.exports.update (node_modules/steamcommunity/node_modules/cheerio/lib/parse.js:55:25)
    at module.exports (node_modules/steamcommunity/node_modules/cheerio/lib/parse.js:17:11)
    at Function.exports.load (node_modules/steamcommunity/node_modules/cheerio/lib/static.js:19:14)
    at node_modules/steamcommunity/components/confirmations.js:20:19
    at SteamCommunity._checkHttpError (node_modules/steamcommunity/index.js:313:3)
    at Request._callback (node_modules/steamcommunity/components/confirmations.js:152:16)
    at Request.self.callback (node_modules/steamcommunity/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (node_modules/steamcommunity/node_modules/request/request.js:1035:10)
    at Request.emit (events.js:129:20)
```

**Comment by DoctorMcKay** [comment]
Caused by #22.
