### ISSUE TITLE
community.postUserComment() bug

### ISSUE THREAD

**Issue by 404ProgramNotFound** [DoctorMcKay/node-steamcommunity#248]
when i try to post a comment on a person's profile 
``` javascript
user.on('friendMessage',function(sid,message){
    if(message=="!test"){
        community.postUserComment(sid,sign,(error)=>{
            if(error) {console.log("error posting: %s",error)}
        });
    }
    
});
```
it give me all time same error and I have no limited account I'm Lvl 20 more then 20 euros spent etc

ERROR:
error posting: Error: The settings on this account do not allow you to add comments.
    at SteamCommunity.<anonymous> (C:\Users\User\Desktop\BotSteam\node_modules\steamcommunity\components\users.js:156:13)
    at Request._callback (C:\Users\User\Desktop\BotSteam\node_modules\steamcommunity\components\http.js:67:15)
    at Request.self.callback (C:\Users\User\Desktop\BotSteam\node_modules\request\request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (C:\Users\User\Desktop\BotSteam\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:310:20)
    at Gunzip.<anonymous> (C:\Users\User\Desktop\BotSteam\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at Gunzip.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)

**Comment by Mr-VIT** [comment]
This string from Steam response `The settings on this account do not allow you to add comments`

**Comment by 404ProgramNotFound** [comment]
I have set the cookies wrong that was the problem
