### ISSUE TITLE
Steam redirect not handled properly

### ISSUE THREAD

**Issue by Noobgam** [DoctorMcKay/node-steamcommunity#334]
For now I'm not exactly sure how to inject into this to see the response, I'll try to investigate if I get to it
But it seems that the redirect isn't handled properly

steamcommunity ver: `3.48.0`

```
/app/node_modules/steamcommunity/components/http.js:94
        if (response.statusCode >= 300 && response.statusCode <= 399 && response.headers.location.indexOf('/login') != -1) {
                                                                                                  ^

TypeError: Cannot read properties of undefined (reading 'indexOf')
    at SteamCommunity._checkHttpError (/app/node_modules/steamcommunity/components/http.js:94:92)
    at Request._callback (/app/node_modules/steamcommunity/components/http.js:50:61)
    at self.callback (/app/node_modules/request/request.js:185:22)
    at Request.emit (node:events:519:28)
    at Request.<anonymous> (/app/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:519:28)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:633:28)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
```

I will try to bump the package as well, but I doubt the cookie changes are specifically related to this error.

**Comment by Noobgam** [comment]
For me it happens after about 2 days of runtime of the bot, so it could be cookies as well, but alas, still probably a bug in response parsing

**Comment by Noobgam** [comment]
Did not happen for a few days after the bump of the library.
Assume the automatic cookie refresh mechanism helped.
