### ISSUE TITLE
Error 429

### ISSUE THREAD

**Issue by dolanmiu** [DoctorMcKay/node-steamcommunity#45]
Hi, I am getting these 429 errors only sometimes:

What do they mean?
```
Dec 19 17:51:43 app/web.1:  Unhandled rejection Error: HTTP error 429 
Dec 19 17:51:43 app/web.1:      at SteamCommunity._checkHttpError (/app/node_modules/steamcommunity/index.js:332:15) 
Dec 19 17:51:43 app/web.1:      at Request._callback (/app/node_modules/steamcommunity/components/users.js:260:12) 
Dec 19 17:51:43 app/web.1:      at Request.self.callback (/app/node_modules/request/request.js:198:22) 
Dec 19 17:51:43 app/web.1:      at emitTwo (events.js:87:13) 
Dec 19 17:51:43 app/web.1:      at Request.emit (events.js:172:7) 
Dec 19 17:51:43 app/web.1:      at Request.<anonymous> (/app/node_modules/request/request.js:1035:10) 
Dec 19 17:51:43 app/web.1:      at emitOne (events.js:82:20) 
Dec 19 17:51:43 app/web.1:      at Request.emit (events.js:169:7) 
Dec 19 17:51:43 app/web.1:      at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:962:12) 
Dec 19 17:51:43 app/web.1:      at emitNone (events.js:72:20) 
Dec 19 17:51:43 app/web.1:      at IncomingMessage.emit (events.js:166:7) 
Dec 19 17:51:43 app/web.1:      at endReadableNT (_stream_readable.js:905:12) 
Dec 19 17:51:43 app/web.1:      at doNTCallback2 (node.js:452:9) 
Dec 19 17:51:43 app/web.1:      at process._tickDomainCallback (node.js:407:17) 
```

**Comment by jwigley** [comment]
429 - too many requests

https://tools.ietf.org/html/rfc6585#section-4

**Comment by DoctorMcKay** [comment]
See @jwigley's link or https://httpstatuses.com/429

**Comment by dolanmiu** [comment]
What is the request/second steam would allow?
