### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by potato20** [DoctorMcKay/node-steamcommunity#61]
When trying to get trade history, via `getInventoryHistory()`

```

/home/joe/myproj/node_modules/steamcommunity/components/inventoryhistory.js:85
				econItem = historyInventory[match[1]][match[2]][match[3]];
				                                 ^

TypeError: Cannot read property '1' of null
    at Request._callback (/home/joe/myproj/node_modules/steamcommunity/components/inventoryhistory.js:85:38)
    at Request.self.callback (/home/joe/myproj/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/joe/myproj/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/joe/myproj/node_modules/request/request.js:962:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)
```

Any idea what could cause this? Doesn't happen all the time, just sometimes.

**Comment by potato20** [comment]
nvm was using an older version (3.14)
